### ISSUE TITLE
현재 발견한 문제점

### ISSUE THREAD

**Issue by wjdtkdgns777** [path-makers/pathfinder-frontend#1]
게시글 API연결후 발생한 문제
유저 이름이 제대로 보여지지 않음 - API 수정될 예정
시간이 제대로 표현되지 않음 - 확인필요
게시글이 올린 순서대로 보여지지 않음

**Comment by 071yoon** [comment]
제가 생각하는 게시글 올린 순서대로 보여지지 않는것 해결법들
1. client 딴에서 createdAt을 보고 정렬
2. 제가 무조건 createdAt 순서로 정렬해서 전송 (요게 맞을거 같긴해여)
3. /api/board/all?order=date 요런식으로 date로 정렬해달라고 query param을 하나 더 생성 (요게 이따 order=recommend 처럼 다양한 정렬법이 나오면 더 활용적일 수 있어요)

그리고 시간이 제대로 표지되지 않는건 제가 Java 내장 date type으로 현재 timestamp(new Date())를 찍어서 올려드린거라 (firebase에서 제공하는 timestamp가 아니여서 충돌이 났을 수 도 있어요) 아마 kotlin에서 지원하는 일반 date type으로 변환하시면 제대로 나올 거 같아용

**Comment by wjdtkdgns777** [comment]
유저 이름과 게시글 올린 순서는 백엔드에서, 시간표시는 코틀린에서 해결
